#!/bin/bash
exename=$(basename $0)
prj_dir=~/workspace/selfsrc/config
backup=$prj_dir/configbackup-master
echo $exename
case $1 in
    copy)
cp -r ~/shell/ $backup
cp -r ~/.vim $backup
cp ~/.vimrc $backup
cp ~/.tmux.conf $backup
cp ~/.gitconfig $backup
cp ~/.gdbinit $backup
cp -r ~/.muttrc $backup/mail
cp -r ~/.esmtprc $backup/mail
cp -r ~/.procmailrc $backup/mail
cp -r ~/.fetchmailrc $backup/mail
cp -r ~/.mailcap $backup/mail
cp -r ~/.w3m $backup/
cp -r ~/.bashrc $backup/
cp -r ~/.bash_aliases $backup/
	cp ~/.gitmsg.txt $backup/
        ;;
    set)
	cp -rf $backup/shell/ ~/shell
	cp -rf $backup/.vim ~/.vim
        cp -f $backup/.tmux.conf ~/.tmux.conf
	cp -f $backup/.gitconfig ~/.gitconfig
	cp -f $backup/.gdbinit ~/.gdbinit
	#cp -f $backup/mail/.muttrc ~/.muttrc
	#cp -f $backup/mail/.esmtprc ~/.esmtprc
	#cp -f $backup/.w3m ~/.w3m
	#cp -f $backup/.bashrc ~/.bashrc
	#cp -f $backup/.bash_aliases ~/.bash_aliases
	cp -f $backup/.gitmsg.txt ~/.gitmsg.txt
	;;
    clone)
	git clone https://github.com/chenyi/config.git
        ;;
    add)
	cd $backup; 
	rm .w3m/w3mtmp* .w3m/w3msrc* .w3m/w3mcache* .w3m/w3mcookie*
	git add -u .; git commit -m "`date`"
        ;;
 
    *)
        ;;
esac
